metadew/iesi

core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/script/ScriptLogOutput.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionControl.java
if the parameter 'output' is set somewhere in the script execution and script.logoutput is used as the last action of a script, both will cause the result 'output' to be written to the DB for the current run_id and process_id causing a primary key constraint failure 
**Id**
3ddf340
=> Double logging of script output causes primary key error

.github/ISSUE_TEMPLATE/documentation_request.md, core/java/iesi-core/pom.xml, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/DataInstructionRepository.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/number/NumberBetween.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/number/NumberBetweenTest.java
Currently the {{*number.between()}} function returns a decimal value ex:
result=resolved {{*number.between("1","120")}} to 32.596405830858956
Unfortunately this can not be used in cases where an integer (whole number) is expected.
**Describe the solution you'd like**
Additional function parameter that would specify amount of decimals (ex: 0 = whole number,...)
**Id**
71f29e3
=> Addition to {{*number.between()}} function

core/bin/iesi-encrypt.sh, core/bin/iesi-launch.sh, core/bin/iesi-metadata.sh, core/bin/iesi-rest.sh, core/bin/iesi-server.sh
When using the .sh scripts in a service file, the service will not start because the current_dir uses $(pwd) and that is not the directory where the script is located.
Using BASH_SOURCE will make sure the script works no matter where you start it from.
=> use bash source for current dir

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/actiontypes/ActionTypeController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/connectiontypes/ConnectionTypeController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/result/ScriptResultController.java
At the moment, a mix of the camel case, hyphen and underscore naming conventions is used for the REST endpoints. This should be standardized to one naming convention.
As a naming convention we propose to use hyphens to separate words in an url.
**id**: a26ac18
=> Standardize endpoint naming convention

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionRuntime.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/lookup/ListLookup.java
when executing the instruction {{=list(\<list\>, \<element\>}}, I want to be able to define \<list\> as a string referencing a previously stored array.
**Id**
cb705b3
=> Allow fetch element from list with list reference name 

core/conf/application-metadata.yml, core/java/iesi-core/src/main/java/io/metadew/iesi/component/http/HttpComponentDesignTraceService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/component/http/HttpComponentService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/component/http/HttpComponentTraceService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/component/trace/ComponentDesignTraceConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/component/trace/ComponentTraceConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/connection/trace/ConnectionTraceConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/connection/trace/ConnectionTrace.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/connection/trace/http/HttpConnectionTrace.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/connection/trace/http/HttpConnectionTraceService.java, core/java/iesi-core/src/main/resources/application-metadata.yml, core/java/iesi-core/src/test/java/io/metadew/iesi/connection/http/HttpConnectionTraceServiceTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/metadata/definition/ComponentDesignTraceConfigurationTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/metadata/definition/ComponentTraceConfigurationTest.java, core/java/iesi-core/src/test/resources/application-metadata.yml, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-metadata.yml, core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-metadata.yml
The table for TraceHttpComponentHeaderDesign and TraceHttpComponentQueryDesign have columns HEADER_DES_ID and QUERY_DES_ID that should be renamed to HTTP_COMP_DES_ID
**id**
c68ec60
=> Http Component Header & Query traces have a faulty column name

core/java/iesi-core/src/main/java/io/metadew/iesi/connection/http/entity/json/ApplicationJsonHttpResponseEntityService.java, core/java/iesi-core/src/test/java/io/metadew/iesi/connection/http/entity/json/ApplicationJsonHttpResponseEntityServiceTest.java
When an API returns an empty string as a JSON response, the framework throws a NullPointerExcpetion. Instead the framework should log a warning and continue the execution.
**Id**
b1cced5
=> Handle empty JSON response

core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/sql/SqlEvaluateResult.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/sql/SqlExecuteProcedure.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/sql/SqlExecuteQuery.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/sql/SqlExecuteStatement.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteQueryPing.java, dev/feature/3424dfb.unknown-connection-sqlexecutequery/HelloWorldScript.yml, dev/feature/3424dfb.unknown-connection-sqlexecutequery/bigquery1.yml, dev/feature/3424dfb.unknown-connection-sqlexecutequery/bigquery2.yml, dev/feature/3424dfb.unknown-connection-sqlexecutequery/db.bigquery.1.yml, dev/feature/3424dfb.unknown-connection-sqlexecutequery/iesi-dev.yml
Eg in SqlExecuteQuery, the connection is setup and assumed to be ok. Subsequent DB actions on the non existing connecting give nullpointer exceptions. Propose to check connection established and handle exceptions early.
```
DatabaseConnection databaseConnection = connectionOperation
.getDatabaseConnection(connection);
if(databaseConnection == null) {
//handle
}
```
**ID**
3424dfb
=> Handle non-established connection 

core/java/iesi-core/pom.xml, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/text/TextSubstring.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/text/TextSubstringTest.java
When executing the text.substring I want to have to have two options:
1. I define both the start and end index
2. I only define the start index
When defining both start and end index (text.substring(\<string>, \<begin index>, \<end index>)) I want the following to happen:  
text.substring(John Doe, 1, 4)--> John
When defining only the start index (text.substring(\<string>, \<begin index>)) I want the following to happen:
text.substring(John Doe, 6)--> Doe
**Id**
ab1a36e
=> allow only defining begin index for text.substring

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/time/TimeFormat.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/time/TimeFormatTest.java
When executing the time.format I want to have to have two options:
1. I define the original timestamp, the format of the original timestamp and the format of the desired timestamp
2. I define the original timestamp and the format of the desired timestamp. Here the original timestamp format is assumed to be 'yyyy-MM-dd HH:mm:ss.SSS'
**da4f2e3**
=> Allow time.format to receive 3 parameters like date.format

core/java/iesi-rest-without-microservices/docs/iesi-openapi.yaml, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/ScriptController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/version/ScriptVersionDto.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/ScriptControllerTest.java
I want to be able to download the raw JSON representation of a script by targeting a specific endpoint.
endpoint: GET /scripts/\<name>/\<version>
headers: Accept application/octet-stream
**Id**
7ef3cff
=> Allow download of script configuration from API

core/java/iesi-core/src/main/java/io/metadew/iesi/connection/tools/FolderTools.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/keyvalue/KeyValueDatasetService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/metadata/DatasetMetadata.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/http/HttpExecuteRequest.java, core/java/iesi-core/src/main/resources/application-repository.yml, core/java/iesi-core/src/main/resources/application.yml, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/disabled/DisabledWebSecurityConfiguration.java, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml
When storing the output of a http.executeRequest in a dataset I want to be able to give an already existing dataset. The expected behaviour is that the dataset will be updated with the latest output
**Id**
d946992
=> http.executeRequest should update output dataset for override

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/IESIMetadataRepositoryConfiguration.java, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/dto/DatasetDtoRepositoryTest.java, core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-repository.yml
```
***************************
APPLICATION FAILED TO START
***************************
Description:
The bean 'metadataRepositoryConfiguration', defined in class path resource [io/metadew/iesi/server/rest/configuration/MetadataRepositoryConfiguration.class], could not be registered. A bean with that name has already been defined in URL [jar:file:/home/robbe/git/iesi/core/java/iesi-rest-without-microservices/target/iesi-rest-0.6.0.jar!/BOOT-INF/classes!/io/metadew/iesi/server/rest/configuration/MetadataRepositoryConfiguration.class] and overriding is disabled.
Action:
Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```
**ID**
3499bf3
=> IESI rest server complains about duplicate bean name 

core/java/iesi-core/src/main/java/io/metadew/iesi/connection/http/response/HttpResponseService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/DataTypeHandler.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/DatasetConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/DatasetImplementationConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/IDatasetImplementationService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/inmemory/InMemoryDatasetImplementationKeyValueConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/inmemory/InMemoryDatasetImplementationService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/data/DataSetDatasetConnection.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/lookup/DatasetLookup.java, core/java/iesi-core/src/test/java/io/metadew/iesi/connection/http/entity/json/ApplicationJsonHttpResponseEntityServiceTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/dataset/DatasetBuilder.java, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/dataset/DatasetConfigurationTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/dataset/implementation/inmemory/InMemoryDatasetImplementationKeyValueConfigurationTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/dataset/implementation/inmemory/InMemoryDatasetImplementationServiceTest.java
When a new data item is added to a dataset implementation, the entire implementation is removed and recreated.
**Expected behavior**
The data item should be updated if it already exists. If the data item does not exist it should be created from scratch.
**Id**
8df23ab
=> Dataset implementation item creation causes full delete and create  

core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ComponentParser.java, core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/ComponentParserTest.java
When providing a openapi documentation with a version as a string I get the following error
```
2021-03-31 15:47:34,906 ERROR [o.a.c.c.C.[.[.[.[dispatcherServlet]] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Request processing failed; nested exception is java.lang.NumberFormatException: For input string: "1.0.6-SNAPSHOT"] with root cause
java.lang.NumberFormatException: For input string: "1.0.6-SNAPSHOT"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_282]
at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_282]
at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_282]
at io.metadew.iesi.openapi.ComponentParser.parse(ComponentParser.java:42) ~[classes/:?]
at …
```
=> OpenAPI transformation - handle version as string 

core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/inmemory/InMemoryDatasetImplementationService.java, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/dataset/implementation/inmemory/InMemoryDatasetImplementationServiceTest.java
When a API response body is of type json, is saved to a dataset and the json body contains a field called body,  a SQL unique constraint exception is thrown on a label name
**Root cause**
The label 'body' is used twice by the framework. Once to save the entire body, once to save the 'body' field of the body
**Id**
32808d3
=> allow json response body of api to contain field named 'body'

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/DataInstructionRepository.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/text/TextReplace.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/text/TextReplaceTest.java
Add an data instruction that will take three arguments:
* source text, the original text
* character to be replaced
* character to be used for replacement
The new data instruction, text.replace(\<source text>, \<character to be replaced>, \<character to be used for replacement>) should replace all the 'character to be replaced' in the 'source text' with the 'character to be used for replacement'.
**Examples**
* text.replace("source text", "t",  "d") -> source dexd
* text.replace("source text", "f",  "d") -> source text
* text.replace("source text", " ",  "") -> sourcetext
* text.replace("source text", "t",  "") -> source ex
**Starting point**
* Similar instruction: io.metadew.iesi.script.execution.instruction.data.text.TextSubstring
* …
=> add text replace instruction

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/connection/dto/ConnectionDtoRepository.java
Make sure that the API returns the String value instead of the SerialClob value
=> bug: connection parameters are presented as SerialClobs instead of string

core/conf/application-action-types.yml, core/java/iesi-core/src/main/resources/application-action-types.yml, core/java/iesi-core/src/test/resources/application-action-types.yml, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-action-types.yml, core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-action-types.yml
Screen: Script Design
Functionality: add action of type "http.executeRequest"
Actual:
- Spelling mistakes in the description for "headers" & "queryparameters" - (Additionnal instead of Additional)
Expected:
- No spelling mistake in the description for "headers" & "queryparameters"
Remark: this is a heavily used actiontype, therefore, logging spellingmistakes in order to be clean & aligned.
=> Script Design - Action Type: http.executeRequest - Spelling Mistake

core/conf/application-connection-types.yml, core/java/iesi-core/src/main/resources/application-connection-types.yml, core/java/iesi-core/src/test/resources/application-connection-types.yml, core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-connection-types.yml
Screen: Connections
Functionality: Create connection
**Actual:**
- When selecting type 'http' and add environment - two mandatory parameters are shown: "baseUrl" & "tls"
- Missing mandatory parameter: "host"
- If not provided, connection give error when executed
**Expected:**
- When selecting type 'http' and add environment - three mandatory parameters are shown: "baseUrl" - "tls" - "host"
=> Connection Creation - HTTP Connection Type - Missing Mandatory Field

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/text/TextReplace.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/text/TextReplaceTest.java
TextReplace Instruction is not working for some of the special characters like ., +, *, ?, ^, $, (, ), [, ], {, }, |, \.
=> TextReplace Instruction functionality is not working for special characters.

core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/cli/CliExecuteCommand.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/data/DataOutputDataset.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/data/DataSetDatasetConnection.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkSetIteration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/http/HttpExecuteRequest.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/socket/SocketTransmitMessage.java
Screen: Scripts
Functionality: Add action of type: http.executeRequest to script - field "Proxy"
**Actual:**
- Incorrect behavior when adding & removing a value for the parameter "Proxy" (optional field)
Steps to reproduce:
- Empty value for field Proxy - Save script
- Add value for field Proxy - Save script
- Remove value for field Proxy - Save script
- Execute script
Error: http.executeRequest does not accept class io.metadew.iesi.datatypes._null.Null as type for proxy connection name
**Expected:**
- Since "Proxy" is an optional field, it may not impact the execution when provided an empty value.
**Starting point
java\io\metadew\iesi\script\action\http\HttpExecuteRequest.java
=> Script Design - Action Type: http.executeRequest- Remove proxy value

core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ComponentParser.java, core/java/iesi-core/src/test/java/io/metadew/iesi/openapi/ComponentParserTest.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/connection/dto/ConnectionDtoResourceAssembler.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/dto/TransformResultDtoResourceAssembler.java
Screen: Components
Functionality: Design components by using the 'load openAPI documentation'-functionality
Dummy file: use the openapi3.yml for testing purposes
**To Reproduce**
Steps to reproduce the behavior:
1. go to 'Components'- screen
2. click on 'Load OpenAPI documentation'
3. Upload the openapi3.yml by using 'Choose a file' functionality
4. Click on validate
**Expected behavior**
Component(s) draft and/or error display gets shown
**Actual behavior**
Errorcode: **Error: {"errorCode":"400","error":"Something is wrong in your documentation","message":"We found the following errors : \n - The version should be a number \n"}**
while correct standard is applied (openAPI3)
If version is correct then also getting Unsupported operation Exception.
=> Component Design - Load OpenAPI Documentation - version format error

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/DataInstructionRepository.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/number/NumberFormat.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/number/NumberFormatTest.java
I want a new instruction that allows me to reformat numbers based on a give target format.
* name: number.format
* parameters:
* number: text, the number that needs to be reformatted
* format: text, the format in Java String#format syntax (https://dzone.com/articles/java-string-format-examples section Formatting an Integer)
* return: the textual representation of the number reformatted with the given format
=> allow number formatting

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/environment/EnvironmentsController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/environment/dto/EnvironmentDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/environment/dto/EnvironmentDtoService.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/environment/dto/IEnvironmentDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/environment/dto/IEnvironmentDtoService.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/configuration/security/jwt/EnvironmentsControllerSecurityTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/environment/dto/EnvironmentDtoRepositoryTest.java
create a new GET /environment/list endpoint allowing to the environments to be fetched in a non paginated way. This is needed to allow the UI to fetch ALL of the environments when the user wants to execute a script.
extend api doc from metadew/iesi-api-documentation#22
extend code from #352
=> fetch all environments unpaginated

core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/script/ScriptConfiguration.java
Screen: Script Design (detail)
Functionality: Perform edit on existing action (action parameters - description)
Description: Performed changes/edits on an existing action are not stored when saving the modifications. Original input remains.
Steps to reproduce:
Open script design & modify existing action (e.g. change the action description)
Save the modification in current script version (Save > Update current version)
Leave the script design screen (e.g. go back to script overview)
Lookup the modified script/actions
Actual:
= original description still visible - edit(s) were not stored
Expected:
= modified/updated description is visible - edit(s) were correctly stored
=> Script Design - Action Edits - Changes not stored

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/encrypter/EncryptionController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/encrypter/EncryptionService.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/encrypter/IEncryptionService.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/encrypter/dto/EncryptDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/encrypter/dto/EncryptPostDto.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/encrypter/EncryptionControllerTest.java
**ID**
187d769
Currently, we can encrypt data by providing the values to be encrypted through the terminal. 
It is better now to be able to execute this process from an API call through an endpoint.
=> Add encryption api endpoint to encrypt values

core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/http/HttpExecuteRequest.java
**ID**
7dfbfa6
**Steps to reproduce**
- Go to actiontype: http.executeRequest
- Enter value for field requestVersion + save action
- Delete value for field requestVersion + save action
- error: http.executeRequest does not accept class io.metadew.iesi.datatypes._null.Null as type for request name
**Conclusion**
when actionparameter ‘requestVersion’ for actiontype: http.executeRequest has been modified/tampered, it does not use the default latest version when value gets deleted/empty – when actionparameter ‘requestVersion’ has not been modified/tampered before (i.e. untouched/left empty), it does take the default latest version
=> Cannot provide empty request version

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/component/dto/ComponentDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/connection/dto/ConnectionDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/dto/DatasetDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/environment/dto/EnvironmentDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/security_group/SecurityGroupDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/user/UserDtoListResultSetExtractor.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/user/UserDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/user/team/TeamDtoRepository.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/component/dto/ComponentRepositoryDtoTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/connection/dto/ConnectionDtoRepositoryTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetDtoRepositoryTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/environment/dto/EnvironmentDtoRepositoryTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/user/UserDtoRepositoryTest.java
**ID**
a0cd7c9
Able to sort data in the UI by name by ignoring the case sensitivity. Even a name begins with an higher letter than another but in uppercase, it will be after the lower letter, and not before.
=> Ignore case when sorting data in the UI
