core/java/iesi-core/src/io/metadew/iesi/script/execution/ExecutionRuntime.java
#25 
Do not find the last closing braces but the first ones
=> indexOf(variable_char_close)

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/date/DateTravel.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/DateTravelTest.java
=> Feature/5 b184 f3/timetravel exclude weekdays or weekend

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/math/AbstractOperationTwoArg.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/math/Addition.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/math/BinaryArithmeticOperation.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/math/Division.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/math/Exponentiation.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/math/Multiplication.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/math/Substraction.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/math/AdditionTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/math/DivisionTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/math/ExponentiationTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/math/MultiplicationTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/math/SubstractionTest.java
0bfbe77
Allow mathematical functions to be used in scripts. The following functions should be provided as a data generation function
* addition {{*math.add(operator1, operator2)}}
* subtraction  {{*math.subtract(operator1, operator2)}}
* division {{*math.divide(operator1, operator2)}}
* multiplication {{*math.multiply(operator1, operator2)}}
* exponentiation {{*math.power(operator1, operator2)}}
=> Allow mathematical functions for data generation

core/assembly/file-assembly.conf, core/bin/iesi-rest.cmd, core/bin/iesi-rest.sh, core/bin/iesi-setenv.sh, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/text/TextServiceTest.java, core/java/iesi-rest-without-microservices/src/main/resources/application-http.yml, core/java/iesi-rest-without-microservices/src/main/resources/application-https.yml
When launching a command, a warning is issued on a missing file in the distributtion
cp: cannot stat '/iesi/v0.2.0/conf/log4j2.xml': No such file or directory
OS: debian 9
JVM: 1.8.0_232
=> Release v0.2.0: issue on log file

docs/pages/contribute/contribute.md, docs/pages/contribute/development.md, docs/pages/documentation.md
Provide documentation on how to set up a development machine for contributing
**Describe the solution you'd like**
Additional page in the documents section detailing how to set up the development environment and build the solution
**Describe alternatives you've considered**
NA
**Additional context**
NA
ID
4acc418
=> Provide development machine configuration documentation

deploy/gcp/assemble.sh, docs/pages/deploy/gcp/apply-terraform-code.md, docs/pages/documentation.md
Create a script to assembly the terraform configurations inside the workspace for execution. This allows to test and package the assets while keeping the repository clean.
**Describe the solution you'd like**
Shell script for assembly of terraform scripts
**Describe alternatives you've considered**
NA
**Additional context**
NA
ID
f33132b
=> Script to assemble GCP terraform configurations for execution in workspace

core/java/iesi-core/src/main/java/io/metadew/iesi/common/crypto/FrameworkCrypto.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/HttpRequestComponentParameterService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/HttpRequestComponentService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/http/HttpExecuteRequest.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/operation/ActionParameterOperation.java
When providing an encrypted parameter to an action, it does not get decrypted. Instead the encryption string is provided
**Id**
652ec1d
=> Encrypted action parameters do not get decrypted 

docs/pages/documentation.md, docs/pages/tutorial/createfirstconnection.md, docs/pages/tutorial/executescript.md, docs/pages/tutorial/executescriptusingparameterlist.md, docs/pages/tutorial/helloworldscript.md, docs/pages/tutorial/loadconfiguration.md, docs/pages/tutorial/tutorialenvironment.md, docs/pages/tutorial/workingwithscriptversions.md
**To what scenario is your documentation request related? Please describe.**
Refine and clarify some of the quick start tutorials
**Additional context**
e888045
=> Clarification of QuickStart tutorials

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoRepository.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/ScriptControllerTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/dto/ScriptDtoServiceTest.java
The paginated /scripts endpoint should be able to be sorted by Name
**Id**: 3c161d5
=> Scripts endpoint sorting by name

core/java/.gitignore, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkSetEnvironment.java, dev/feature/be20731.setenv-exists/SetenvScript.yml, dev/feature/be20731.setenv-exists/Tutorial2Environment.yml, dev/feature/be20731.setenv-exists/TutorialEnvironment.yml, docs/pages/design/actiontypes/fwk.setEnvironment.md
When setting the environment in a script using the fwk.setEnvironment action, verifiy if the selected env exists
**ID**
be20731
=> fwk.setEnvironment - add check if environment exists before changing

core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/cli/CliExecuteCommand.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/data/DataCompareDataset.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/eval/EvalAssertEquals.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/eval/EvalExecuteExpression.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/eval/EvalListContains.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/eval/EvalVerifyMandatoryField.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoExecuteFileTransfer.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkExecuteScript.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkSetEnvironment.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/mod/ModSoapui.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/r/RExecuteScript.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/r/RPrepareWorkspace.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/r/RStartShinyApp.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/r/RStopShinyApp.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/sql/SqlEvaluateResult.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteFilePing.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteQueryPing.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteWait.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaGetConfirmation.java
In order for the UI to display error messages, the actions should output a 'action.error' message when it encounters an error
**id**
33e34d0
=> All actions increase the error count should also output a 'action.error' message

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ActionControl.java
It should be able to log datatypes to the database. The logging procedure should write an interpreted version of the datatype to the database
**Id**
f021b19
=> log output of any datatype to the database

core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/action/ActionParameterTraceService.java
Resolved action parameters of type Dataset, Array and Template are not visualized in the UI
**Id**
4318ce2
=> action parameters of type Dataset, Array and Template are not visualized in the UI

core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/eval/EvalAssertEquals.java
Comparing an expected template to an actual dataset should try to match the dataset to the template instead of matching it key by key
**Id**
0c89cd9
=> Datasets and Templates are not allowed to be compared 

core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/execution/script/ScriptExecutionRequestConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/execution/script/ScriptExecutionRequestImpersonationConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/execution/script/ScriptExecutionRequestParameterConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptExecutionRequest.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptExecutionRequestBuilder.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptFileExecutionRequest.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/execution/script/ScriptNameExecutionRequest.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDtoModelAssembler.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/script/dto/ScriptExecutionRequestDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/script/dto/ScriptExecutionRequestDtoModelAssembler.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestRepositoryDtoTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/script/dto/ScriptExecutionRequestDtoTest.java
Add script run status to script execution requests fetch API call once available
**Id**
a912346
=> Add script run status to script execution requests fetch API call once available

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/actiontypes/ActionTypeController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/component/ComponentsController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/disabled/DisabledWebSecurityConfiguration.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/jwt/JwtWebSecurityConfiguration.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/connection/ConnectionsController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/connectiontypes/ConnectionTypeController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/environment/EnvironmentsController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/impersonation/ImpersonationController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/ScriptController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/scriptExecutionDto/ScriptExecutionDtoController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/scriptResultDto/ScriptResultController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/user/UserController.java
=> CORS error for PUT and DELETE endpoints

core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/action/ActionParameterTraceService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/action/ActionTraceService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/script/ScriptTraceService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ActionExecution.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ActionRuntime.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionControl.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionTrace.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ScriptExecution.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/operation/ActionParameterOperation.java
=> Resolved parameters not stored when execute phase of an action fails

core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/DatasetConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/DatasetImplementationConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/action/key/ActionKey.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/component/key/ComponentAttributeKey.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/component/key/ComponentKey.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/script/key/ScriptParameterKey.java, core/java/iesi-core/src/test/java/io/metadew/iesi/metadata/configuration/dataset/DatasetConfigurationTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/metadata/definition/ComponentDesignTraceConfigurationTest.java, core/java/iesi-rest-without-microservices/docs/iesi-openapi.yaml, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/DatasetController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/dto/DatasetDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/dto/DatasetDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/dto/DatasetImplementationLabelPostDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/dto/DatasetImplementationPostDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/dto/DatasetPostDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/dto/InMemoryDatasetImplementationKeyValuePostDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/dto/InMemoryDatasetImplementationPostDto.java
A dataset without implementations is not found by the framework
**id**
0a42df3
=> not able to retrieve a dataset without implementations

.circleci/config.yml, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/user/TeamListResultSetExtractor.java, core/java/iesi-core/src/test/java/io/metadew/iesi/connection/elasticsearch/filebeat/DelimitedFileBeatElasticSearchConnectionTest.java, core/java/iesi-rest-without-microservices/pom.xml, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/security/jwt/JwtWebSecurityConfiguration.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/DatasetDtoModelAssembler.java, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi.yml, core/java/iesi-rest-without-microservices/src/main/resources/log4j2.xml, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetModelAssemblerTest.java
=> enhance logging of REST server

core/java/iesi-core/src/main/java/io/metadew/iesi/connection/HostConnection.java, core/java/iesi-core/src/main/java/io/metadew/iesi/connection/operation/ConnectionOperation.java, core/java/iesi-core/src/main/java/io/metadew/iesi/connection/operation/FileTransferService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/connection/tools/HostConnectionTools.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/cli/CliExecuteCommand.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoCreateFolder.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoDeleteFile.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoDeleteFolder.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoExecuteFileTransfer.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoFileExists.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fho/FhoFolderExists.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkExecuteSuite.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteFilePing.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/wfa/WfaExecuteQueryPing.java, core/java/iesi-core/src/main/resources/application-repository.yml, core/java/iesi-core/src/main/resources/application.yml
=> clean up host operations

docs/pages/Use Cases, docs/pages/Use Cases.md
**To what scenario is your documentation request related? Please describe.**
Add new page to documentation & complete content on use cases & testing possibilities.
**Additional context**
3e98a39
=> Create new page - use cases

.circleci/config.yml, core/java/iesi-core/pom.xml, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/eval/EvalListContains.java, core/java/iesi-rest-without-microservices/pom.xml, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi.yml
=> allow list to be reference name for eval.listContains

core/conf/application-action-types.yml, core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ComponentParser.java, core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/ConnectionParser.java, core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPIGenerator.java, core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/OpenAPILauncher.java, core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/Parser.java, core/java/iesi-core/src/main/java/io/metadew/iesi/openapi/TransformResult.java, core/java/iesi-rest-without-microservices/pom.xml, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/configuration/IesiConfiguration.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/IOpenAPIService.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/OpenAPIController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/OpenAPIService.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/dto/TransformResultDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/openapi/dto/TransformResultDtoResourceAssembler.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/openapi/OpenAPIControllerTest.java
Provide an OpenAPI file from an endpoint and returns all the components and connection that have been generated.
=> Transform OpenAPI documentation through REST API

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/ExecutionRuntime.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/DataInstructionRepository.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/date/ListSize.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/date/ListSizeTest.java
Hi Robbe,
Please review changes for newly added ListSize instruction
=> Added list.size() instruction to IESI

core/java/iesi-core/.gitignore, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/DataTypeHandler.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/socket/SocketTransmitMessage.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/lookup/CoalesceLookup.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/lookup/LookupInstructionRepository.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/lookup/CoalesceLookupTest.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/implementation/inmemory/InMemoryDatasetImplementationDto.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/implementation/inmemory/InMemoryDatasetImplementationPostDto.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetsControllerTest.java
=> fix dataset update endpoint and fix typo for socket transmit message

core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/DataTypeHandler.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/array/ArrayService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/dataset/implementation/inmemory/InMemoryDatasetImplementationService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/template/TemplateService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/text/Text.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/service/action/ActionParameterTraceService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkExecuteScript.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkSetParameterList.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkSetParameterValue.java, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/array/ArrayServiceTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/dataset/implementation/inmemory/InMemoryDatasetImplementationServiceTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/datatypes/template/TemplateServiceTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/lookup/CoalesceLookupTest.java
=> fix datatype resolvement and variable resolvement order

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/DataInstructionRepository.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/text/RandomUUID.java
Create a new Instruction that will generate a random UUID
* name: text.uuid
* parameters: none
* return: a textual representation of a randomly generated UUID
=> generate a random UUID

core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/mysql/MysqlDatabaseConnection.java, core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/mysql/MysqlDatabaseService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/netezza/NetezzaDatabaseService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/connection/database/postgresql/PostgresqlDatabaseService.java, core/java/iesi-core/src/test/java/io/metadew/iesi/connection/service/MysqlConnectionServiceTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/connection/service/NetezzaConnectionServiceTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/connection/service/PostgresqlConnectionServiceTest.java
verify all io.metadew.iesi.connection.database.IDatabaseService implementatoin implement io.metadew.iesi.connection.database.IDatabaseService#getDatabase
Also verify that schema definition is mandatory for the database technology in question or not
=> verify database connection creation from IESI connection

core/java/iesi-rest-without-microservices/.gitignore
=> Ignore repository.db3 from git in rest

core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml
Remove local yml changes from #387
=> Remove local-yml-changes

core/java/iesi-core/pom.xml, core/java/iesi-rest-without-microservices/pom.xml
=> Update log4J2 version

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/dataset/DatasetController.java, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-repository.yml, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetsControllerSecurityTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/dataset/DatasetsControllerTest.java
=> Manage dataset in the UI

core/conf/application-metadata.yml, core/java/iesi-core/src/main/resources/application-metadata.yml, core/java/iesi-core/src/test/resources/application-metadata.yml, core/java/iesi-rest-without-microservices/src/main/resources/application-iesi-metadata.yml, core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-metadata.yml
=> Define clob length to action parameter value column to 4000

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/text/XMLPathTraversal.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/text/XMLPathTraversalTest.java
=> Xml documents that contain any kind of spaces between tags are note parsed in the instruction text.xmlpath

core/java/iesi-core/src/main/java/io/metadew/iesi/datatypes/DataTypeHandler.java
=> Eval.AssertEquals cannot evaluate null as text and null datatype

core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/definition/script/ScriptJsonComponent.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/script/ScriptsController.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/builder/script/ScriptDtoBuilder.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/ScriptsControllerTest.java
=> Export script as metadata type

core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/policies/definitions/executionRequests/ExecutionRequestLabelPolicy.java, core/java/iesi-core/src/main/java/io/metadew/iesi/common/configuration/metadata/policies/definitions/scripts/ScriptLabelPolicy.java, core/java/iesi-core/src/test/java/io/metadew/iesi/common/configuration/metadata/policies/definitions/executionRequests/ExecutionRequestPolicyDefinitionTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/common/configuration/metadata/policies/definitions/scripts/ScriptPolicyDefinitionTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestServiceTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/script/ScriptServiceTest.java, core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-policies.yml
=> Able to activate or disactivate a policy

core/java/iesi-core/src/main/java/io/metadew/iesi/connection/http/entity/json/ApplicationJsonHttpResponseEntityService.java
=> Format scientific notation inside application/json response when triggering a http.executeRequest action

core/java/iesi-core/src/main/java/io/metadew/iesi/component/http/HttpComponentService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/component/http/IHttpComponentService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/metadata/configuration/action/trace/ActionParameterTraceConfiguration.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/ActionTypeExecution.java, core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/http/HttpExecuteRequest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/component/http/HttpComponentServiceTest.java, core/java/iesi-core/src/test/java/io/metadew/iesi/script/action/http/HttpExecuteRequestTest.java
=> Cannot visit a specific version of component in the action report detail

core/java/iesi-core/src/main/java/io/metadew/iesi/script/action/fwk/FwkExecuteScript.java
=> Using unexisiting fileParam doesn't throw any exeptions and make the script slower due to unclosed buffer

core/java/iesi-core/src/main/java/io/metadew/iesi/connection/http/entity/_default/DefaultHttpResponseEntityService.java, core/java/iesi-core/src/main/java/io/metadew/iesi/connection/http/entity/json/ApplicationJsonHttpResponseEntityService.java
=> JSON response doesn't format scientific notation for rawbody dataset

core/java/iesi-core/src/main/java/io/metadew/iesi/script/execution/instruction/data/text/TextTrim.java, core/java/iesi-core/src/main/resources/application-repository.yml, core/java/iesi-core/src/test/java/io/metadew/iesi/script/execution/instruction/data/text/TextTrimTest.java
**ID**
bd616f4
Implement new instructions to be able to trim a provided text.
**Example**
AS IF: <pre>                  my text with spaces              will be resolved into "                      my text with spaces             " </pre>
TO BE:  <pre> Using {{*text.trim(        my text with spaces            )}} will be resolved into "my-text-with-spaces" </pre>
=> Trim text value using instruction

core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/component/dto/ComponentDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestController.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestDtoRepository.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestFilterOption.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestService.java, core/java/iesi-rest-without-microservices/src/main/java/io/metadew/iesi/server/rest/executionrequest/dto/ExecutionRequestDtoModelAssembler.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/component/dto/ComponentRepositoryDtoTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestBuilder.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestControllerMvcTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestRepositoryDtoTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/executionrequest/ExecutionRequestsControllerSecurityTest.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/scriptExecutionDto/ScriptExecutionBuilder.java, core/java/iesi-rest-without-microservices/src/test/java/io/metadew/iesi/server/rest/scriptExecutionDto/ScriptExecutionDtoRepositoryTest.java, core/java/iesi-rest-without-microservices/src/test/resources/application-iesi-repository.yml
**ID**
3ae868e3
**AS IS**
Scripts reports can be filtered by script name, run id, timestamp etc.
**TO BE**
Add support to filter the reports by user id
=> Filter reports by user
